name: Create file on server via SSH

on:
  pull_request:
    branches:
      - main

jobs:
  create_file:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Save new added files
      run: |
        git diff --name-only HEAD~1 > added_files.txt
    - name: Save files
      uses: actions/upload-artifact@v2
      with:
        name: added-files
        path: added_files.txt

    - name: Set up SSH
      run: |
        cat added-files.txt >> ~/pr-save.js
