name: Save modified file on pull request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  save-file:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set environment variables
      run: |
        pr_file=`ls | grep -vE "README.md"`
        node $pr_file
      env:
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
   
#     - name: Save modified file in server
#       run: |
#         node ~/actions-runner/_work/AboutHow/AboutHow/$pr_file
