name: Create file on server via SSH

on:
  pull_request:
    branches:
      - main

jobs:
  create_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ssh_key
        chmod 600 ssh_key
        cat ssh_key
        echo "${{ secrets.SSH_KNOWN_HOSTS }}" > known_hosts

    - name: Connect to server and create file
      run: ssh -i ssh_key -o "StrictHostKeyChecking no" intruder@34.142.224.106 "touch myfile.txt"
