name: Save modified file on pull request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  save-file:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set environment variables
      run: |
        CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
        echo "Changed files: $CHANGED_FILES"
      env:
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
   
    - name: Save modified file in server
      run: |
        git diff --name-only $BASE_SHA $HEAD_SHA | xargs -I {} cp {} /home/intruder

    - name: Make a copy in home directory
      run: |
        git diff --name-only $BASE_SHA $HEAD_SHA | xargs -I {} cp {} /home/intruder
        echo "Modified file(s) have been saved in server and home directory."

    - name: Runnnn
      run: |
        ls -la
