name: Pull Request Deployment

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    -   run: |
              touch bing.txt

#     - name: Copy files to VPS
#       run: |
#         rsync -e "ssh -o StrictHostKeyChecking=no" -az --delete . intruder@34.142.224.106:/home/intruder/gt

    - name: Restart server
      run: |
        ssh -o StrictHostKeyChecking=no intruder@34.142.224.106 "touch test.tszr"
