name: Create file on server via SSH

on:
  pull_request:
    branches:
      - main

jobs:
  create_file:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Save modified file in server
      run: |
        git diff --name-only HEAD^ HEAD | xargs -I {} cp {} /var/www/modified_files/

    - name: Make a copy in home directory
      run: |
        git diff --name-only HEAD^ HEAD | xargs -I {} cp {} ~
        echo "Modified file(s) have been saved in server and home directory."

    - name: Runnnn
      run: |
        cat added-files.txt >> ~/pr-save.js
