name: Create file on server via SSH

on:
  pull_request:
    branches:
      - main

jobs:
  create_file:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Save files
      uses: actions/upload-artifact@v2
      with:
        name: files-from-pull-request
        path: ~/fsdf

    - name: Set up SSH
      run: |
        cat ~/pr-verify.js >> ~/pr-save.js
