name: Create file on server via SSH

on:
  pull_request:
    branches:
      - main

jobs:
  create_file:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        touch test.txt
